/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jsons.odontoapp.view;

/**
 *
 * @author Ruben Benavides, Jsons, DCCO-ESPE
 */
public class OdontoApp extends javax.swing.JFrame {

    /**
     * Creates new form OdontoApp
     */
    public OdontoApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnubar = new javax.swing.JMenuBar();
        mnuPatients = new javax.swing.JMenu();
        itmManagement = new javax.swing.JMenuItem();
        mnuServices = new javax.swing.JMenu();
        itmBuy = new javax.swing.JMenuItem();
        mnuAppointments = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("OdontoApp");

        mnubar.setBackground(java.awt.Color.blue);
        mnubar.setForeground(java.awt.Color.red);

        mnuPatients.setText("Pacientes");
        mnuPatients.setToolTipText("");

        itmManagement.setText("Gestión");
        itmManagement.setToolTipText("Presiona para hacer acciones con los pacientes.");
        itmManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmManagementActionPerformed(evt);
            }
        });
        mnuPatients.add(itmManagement);

        mnubar.add(mnuPatients);

        mnuServices.setText("Servicios");

        itmBuy.setText("Comprar");
        itmBuy.setToolTipText("Presiona para comprar servicios para un paciente.");
        itmBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuyActionPerformed(evt);
            }
        });
        mnuServices.add(itmBuy);

        mnubar.add(mnuServices);

        mnuAppointments.setText("Citas");

        jMenuItem1.setText("Gestión");
        jMenuItem1.setToolTipText("Presiona para hacer acciones con las citas de un paciente.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAppointments.add(jMenuItem1);

        mnubar.add(mnuAppointments);

        jMenu3.setText("Ganancias");

        jMenuItem2.setText("Calcular Ganancias");
        jMenuItem2.setToolTipText("Presiona para calcular las ganancias diarias.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        mnubar.add(jMenu3);

        setJMenuBar(mnubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmManagementActionPerformed
        FrmPatients frmPatients = new FrmPatients();
        frmPatients.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmManagementActionPerformed

    private void itmBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuyActionPerformed
        FrmChoosePatient frmChoosePatient = new FrmChoosePatient();
        frmChoosePatient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmBuyActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmBeforeAppointment appointmets = new FrmBeforeAppointment();
        appointmets.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmRevenues revenues = new FrmRevenues();
        revenues.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdontoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdontoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdontoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdontoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdontoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmBuy;
    private javax.swing.JMenuItem itmManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuAppointments;
    private javax.swing.JMenu mnuPatients;
    private javax.swing.JMenu mnuServices;
    private javax.swing.JMenuBar mnubar;
    // End of variables declaration//GEN-END:variables
}
