/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jsons.odontoapp.view;

import com.jsons.odontoapp.controller.IdsControler;
import com.jsons.odontoapp.controller.PatientController;
import com.jsons.odontoapp.model.Appointment;
import com.jsons.odontoapp.model.ClinicalHistory;
import com.jsons.odontoapp.model.Patient;
import com.jsons.odontoapp.model.Service;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruben Benavides, Jsons, DCCO-ESPE
 */
public class FrmPatientToEdit extends javax.swing.JFrame {
    
    PatientController patientController = new PatientController();
    int patientId;
    Patient newPatient = new Patient();
    ClinicalHistory clinicalHistory = new ClinicalHistory();
    ArrayList<Appointment> appointments = new ArrayList<Appointment>();
    ArrayList<Service> acquiredServices = new ArrayList<Service>();
    private IdsControler control;
    
    /**
     * Creates new form FrmPatientToEdit
     */
    public FrmPatientToEdit(Patient patient) {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        control = new IdsControler();
        int id = patient.getClinicalHistory().getId();
        String idString = String.valueOf(id);
        txtId.setText(idString);
        
        txtName.setText(patient.getClinicalHistory().getName());
        
        int age = patient.getClinicalHistory().getAge();
        String ageString = String.valueOf(age);
        txtAge.setText(ageString);
        
        double weight = patient.getClinicalHistory().getWeight();
        String weightString = String.valueOf(weight);
        txtWeight.setText(weightString);
        
        double height = patient.getClinicalHistory().getHeight();
        String heightString = String.valueOf(height);
        txtHeight.setText(heightString);
        
        txtDiseaseSymptoms.setText(patient.getClinicalHistory().getDiseaseSymptoms());
        
        txtCellPhoneNumber.setText(patient.getClinicalHistory().getCellphone());
        
        txtSystemicDiseases.setText(patient.getClinicalHistory().getSystemicDiseases());
        
        txtPatientTreatment.setText(patient.getClinicalHistory().getPatientTreatment());
        
        cdarStarDate.setDate(patient.getClinicalHistory().getTreatmentDateStart());
        
        cdarEndDate.setDate(patient.getClinicalHistory().getTreatmentEndDate());
        
        patientId = patient.getClinicalHistory().getId();

        clinicalHistory = patient.getClinicalHistory();
        acquiredServices = patient.getAcquiredServices();
        appointments = patient.getAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btGoBack = new javax.swing.JButton();
        btnUpdatePatient = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAgeWarning = new javax.swing.JLabel();
        lblWeightWarning = new javax.swing.JLabel();
        lblHeightWarning = new javax.swing.JLabel();
        cdarEndDate = new com.toedter.calendar.JDateChooser();
        lblContactNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientTreatment = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cdarStarDate = new com.toedter.calendar.JDateChooser();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtCellPhoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtSystemicDiseases = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiseaseSymptoms = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        lblNameWarning = new javax.swing.JLabel();
        lblIdWarning = new javax.swing.JLabel();
        btnDupply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btGoBack.setText("Regresar");
        btGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGoBackActionPerformed(evt);
            }
        });

        btnUpdatePatient.setText("Actualizar");
        btnUpdatePatient.setEnabled(false);
        btnUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addComponent(btnUpdatePatient)
                .addGap(391, 391, 391)
                .addComponent(btGoBack))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGoBack)
                    .addComponent(btnUpdatePatient))
                .addContainerGap())
        );

        cdarEndDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cdarEndDatePropertyChange(evt);
            }
        });

        lblContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblContactNumberKeyReleased(evt);
            }
        });

        jLabel4.setText("Fecha de Finalización de Tratamiento:");

        jLabel2.setText("Tratamiento del Paciente:");

        txtPatientTreatment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientTreatmentKeyReleased(evt);
            }
        });

        jLabel12.setText("Enfermedades Sistemáticas:");

        cdarStarDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cdarStarDatePropertyChange(evt);
            }
        });

        txtId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtIdInputMethodTextChanged(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtIdPropertyChange(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });

        jLabel3.setText("Fecha de Inicio de Tratamiento:");

        txtName.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtNameComponentAdded(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtAge.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAgePropertyChange(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWeightKeyReleased(evt);
            }
        });

        txtCellPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellPhoneNumberActionPerformed(evt);
            }
        });
        txtCellPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCellPhoneNumberKeyReleased(evt);
            }
        });

        jLabel1.setText("Altura en m (separe con puntos):");

        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeightKeyReleased(evt);
            }
        });

        txtSystemicDiseases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSystemicDiseasesActionPerformed(evt);
            }
        });
        txtSystemicDiseases.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSystemicDiseasesKeyReleased(evt);
            }
        });

        jLabel6.setText("Id:");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Edad:");

        jLabel9.setText("Peso en kg (separe con puntos):");

        jLabel10.setText("Síntomas:");

        txtDiseaseSymptoms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiseaseSymptomsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiseaseSymptoms);

        jLabel11.setText("Número de contacto:");

        btnDupply.setText("Verificar duplicados");
        btnDupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDupplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDupply))
                    .addComponent(txtPatientTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cdarEndDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdarStarDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSystemicDiseases, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAgeWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHeightWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWeightWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCellPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDupply)
                        .addComponent(lblIdWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAgeWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHeightWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWeightWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCellPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPatientTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSystemicDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cdarStarDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cdarEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGoBackActionPerformed
        FrmEditPatients frmEditPatients = new FrmEditPatients();
        frmEditPatients.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btGoBackActionPerformed

    private void btnUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientActionPerformed
        readTreatmentStartDate();
        readTreatmentEndDate();
        newPatient.setClinicalHistory(clinicalHistory);
        newPatient.setAcquiredServices(acquiredServices);
        newPatient.setAppointments(appointments);
        int option = JOptionPane.showConfirmDialog(this,"Está segura de que desea actualizar con los datos: \n" + newPatient.OnlyPatientsToString(), "saving warning",1);
        if(option == 0){
            JOptionPane.showMessageDialog(rootPane, "saved, saving..");
            patientController.update(patientId, newPatient);
        }
        if(option == 1){
            JOptionPane.showMessageDialog(rootPane, "not saved");
        }
        if(option == 2){
            JOptionPane.showMessageDialog(rootPane, "canceled");
        }
    }//GEN-LAST:event_btnUpdatePatientActionPerformed

    public void verifyFilledFields(){
        if(txtId.getText().isEmpty() ||
           txtName.getText().isEmpty() ||
           txtAge.getText().isEmpty() || 
           txtWeight.getText().isEmpty() ||
           txtHeight.getText().isEmpty() || 
           txtCellPhoneNumber.getText().isEmpty() ||
           txtPatientTreatment.getText().isEmpty() || txtDiseaseSymptoms.getText().isEmpty() ||
           txtSystemicDiseases.getText().isEmpty() || cdarStarDate.getDate() == null ||
           cdarEndDate.getDate() == null ||
           txtId.getText().matches("\\d*") == false ||
           txtName.getText().matches("[A-Za-zá-ú ]*") == false || 
           txtAge.getText().matches("\\d*") == false ||
           txtWeight.getText().matches("\\d*\\.?\\d*") == false ||
           txtHeight.getText().matches("\\d*\\.?\\d*") == false ||
           txtHeight.getText().matches("\\d*\\.?\\d*") == false ||
           txtCellPhoneNumber.getText().matches("[0-9-\\s()]*") == false){
            btnUpdatePatient.setEnabled(false);
        }else{
            if(Integer.parseInt(txtId.getText()) <= 0 ||
               Integer.parseInt(txtAge.getText()) <= 0 ||
               Double.parseDouble(txtWeight.getText()) <= 0 || 
               Double.parseDouble(txtHeight.getText()) <= 0){
                btnUpdatePatient.setEnabled(false);
            }else{
                btnUpdatePatient.setEnabled(true);
            }
        }
    }
    
    public void readTreatmentStartDate(){
        Date treatmentStartDate = cdarStarDate.getDate();
        clinicalHistory.setTreatmentDateStart(treatmentStartDate);
    }
    
    public void readTreatmentEndDate(){
        Date treatmentEndDate = cdarEndDate.getDate();
        clinicalHistory.setTreatmentEndDate(treatmentEndDate);
    }
    
    
    private void cdarEndDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cdarEndDatePropertyChange
        verifyFilledFields();
    }//GEN-LAST:event_cdarEndDatePropertyChange

    private void lblContactNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblContactNumberKeyReleased

    }//GEN-LAST:event_lblContactNumberKeyReleased

    private void txtPatientTreatmentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientTreatmentKeyReleased
        String patientTreatment;
        patientTreatment = txtPatientTreatment.getText();
        clinicalHistory.setPatientTreatment(patientTreatment);
        verifyFilledFields();
    }//GEN-LAST:event_txtPatientTreatmentKeyReleased

    private void cdarStarDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cdarStarDatePropertyChange
        verifyFilledFields();
    }//GEN-LAST:event_cdarStarDatePropertyChange

    private void txtIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtIdInputMethodTextChanged

    }//GEN-LAST:event_txtIdInputMethodTextChanged

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed

    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        int id;
        if (txtId.getText().matches("\\d*") && !txtId.getText().isEmpty()) {
            id = Integer.parseInt(txtId.getText()) ;
            if (id > 0) {
                lblIdWarning.setVisible(false);
                clinicalHistory.setId(id);
            } else {
                lblIdWarning.setText("Ingrese solo numeros positivos");
                lblIdWarning.setForeground(Color.red);
                lblIdWarning.setVisible(true);
                btnUpdatePatient.setEnabled(false);
            }
        }else{
            lblIdWarning.setText("Ingrese solo numeros enteros");
            lblIdWarning.setForeground(Color.red);
            lblIdWarning.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtId.getParent().revalidate();
        txtId.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtNameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtNameComponentAdded

    }//GEN-LAST:event_txtNameComponentAdded

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed

    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        String name;
        if(txtName.getText().matches("[A-Za-zá-ú ]*")){
            lblNameWarning.setVisible(false);
            name = txtName.getText();
            clinicalHistory.setName(name);
        }else{
            lblNameWarning.setText("Ingrese solo nombres validos.");
            lblNameWarning.setForeground(Color.red);
            lblNameWarning.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtName.getParent().revalidate();
        txtName.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

    }//GEN-LAST:event_txtNameKeyTyped

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        int age;
        if (txtAge.getText().matches("\\d*") && !txtAge.getText().isEmpty()) {
            age = Integer.parseInt(txtAge.getText()) ;
            if (age > 0) {
                lblAgeWarning.setVisible(false);
                clinicalHistory.setAge(age);
            } else {
                lblAgeWarning.setText("Ingrese solo numeros positivos");
                lblAgeWarning.setForeground(Color.red);
                lblAgeWarning.setVisible(true);
                btnUpdatePatient.setEnabled(false);
            }
        }else{
            lblAgeWarning.setText("Ingrese solo numeros enteros");
            lblAgeWarning.setForeground(Color.red);
            lblAgeWarning.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtAge.getParent().revalidate();
        txtAge.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyReleased
        double weight;
        if (txtWeight.getText().matches("\\d*\\.?\\d*") && !txtWeight.getText().isEmpty()) {
            weight = Double.parseDouble(txtWeight.getText());
            if (weight > 0) {
                lblWeightWarning.setVisible(false);
                clinicalHistory.setWeight(weight);
            } else {
                lblWeightWarning.setText("Ingrese solo numeros positivos");
                lblWeightWarning.setForeground(Color.red);
                lblWeightWarning.setVisible(true);
                btnUpdatePatient.setEnabled(false);
            }
        } else {
            lblWeightWarning.setText("Ingrese un número válido");
            lblWeightWarning.setForeground(Color.red);
            lblWeightWarning.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtWeight.getParent().revalidate();
        txtWeight.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtWeightKeyReleased

    private void txtCellPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellPhoneNumberActionPerformed

    private void txtCellPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCellPhoneNumberKeyReleased
        String cellphone;
        if (txtCellPhoneNumber.getText().matches("[0-9-\\s()]*")) {
            lblContactNumber.setVisible(false);
            cellphone = txtCellPhoneNumber.getText();
            clinicalHistory.setCellphone(cellphone);
        } else {
            lblContactNumber.setText("Ingrese solo numeros validos.");
            lblContactNumber.setForeground(Color.red);
            lblContactNumber.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtCellPhoneNumber.getParent().revalidate();
        txtCellPhoneNumber.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtCellPhoneNumberKeyReleased

    private void txtHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyReleased
        double height;
        if (txtHeight.getText().matches("\\d*\\.?\\d*") && !txtHeight.getText().isEmpty()) {
            height = Double.parseDouble(txtHeight.getText());
            if (height > 0) {
                lblHeightWarning.setVisible(false);
                clinicalHistory.setHeight(height);
            } else {
                lblHeightWarning.setText("Ingrese solo numeros positivos");
                lblHeightWarning.setForeground(Color.red);
                lblHeightWarning.setVisible(true);
                btnUpdatePatient.setEnabled(false);
            }
        } else {
            lblHeightWarning.setText("Ingrese un número válido");
            lblHeightWarning.setForeground(Color.red);
            lblHeightWarning.setVisible(true);
            btnUpdatePatient.setEnabled(false);
        }
        txtHeight.getParent().revalidate();
        txtHeight.getParent().repaint();
        verifyFilledFields();
    }//GEN-LAST:event_txtHeightKeyReleased

    private void txtSystemicDiseasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSystemicDiseasesActionPerformed

    }//GEN-LAST:event_txtSystemicDiseasesActionPerformed

    private void txtSystemicDiseasesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSystemicDiseasesKeyReleased
        String systemicDiseases;
        systemicDiseases = txtSystemicDiseases.getText();
        clinicalHistory.setSystemicDiseases(systemicDiseases);
        verifyFilledFields();
    }//GEN-LAST:event_txtSystemicDiseasesKeyReleased

    private void txtDiseaseSymptomsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiseaseSymptomsKeyReleased
        String diseaseSymptoms;
        diseaseSymptoms = txtDiseaseSymptoms.getText();
        clinicalHistory.setDiseaseSymptoms(diseaseSymptoms);
        verifyFilledFields();
    }//GEN-LAST:event_txtDiseaseSymptomsKeyReleased

    private void txtAgePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAgePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgePropertyChange

    private void txtIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtIdPropertyChange
        
    }//GEN-LAST:event_txtIdPropertyChange

    private void btnDupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDupplyActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim(); // Reemplaza "txtId" por el nombre de tu JTextField o JTextArea

        // Verificar si el ID ya existe en la base de datos
        boolean idExiste = control.verifyrIdExist(id);

        // Mostrar un JOptionPane con el resultado de la verificación
        if (idExiste) {
            JOptionPane.showMessageDialog(this, "El ID ya existe en la base de datos.", "Verificación de ID", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El ID no existe en la base de datos.", "Verificación de ID", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDupplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPatientToEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPatientToEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPatientToEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPatientToEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGoBack;
    private javax.swing.JButton btnDupply;
    private javax.swing.JButton btnUpdatePatient;
    private com.toedter.calendar.JDateChooser cdarEndDate;
    private com.toedter.calendar.JDateChooser cdarStarDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgeWarning;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblHeightWarning;
    private javax.swing.JLabel lblIdWarning;
    private javax.swing.JLabel lblNameWarning;
    private javax.swing.JLabel lblWeightWarning;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCellPhoneNumber;
    private javax.swing.JTextPane txtDiseaseSymptoms;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientTreatment;
    private javax.swing.JTextField txtSystemicDiseases;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
